# -*- coding: utf-8 -*-
"""Preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rsZsTOKCCCn8y5Fs0UVO3pRxz-NdKDzb
"""

# Import libraries
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import matplotlib.pyplot as plt

# Dataset paths
DATA_DIR = '/content/drive/MyDrive/DL_Assignment/chest_xray/'
train_dir = os.path.join(DATA_DIR, 'train')
val_dir   = os.path.join(DATA_DIR, 'val')
test_dir  = os.path.join(DATA_DIR, 'test')

# --------------------------
# 1. Data Augmentation for Training
# --------------------------
train_datagen = ImageDataGenerator(
    rescale=1./255,           # Normalize pixel values to [0,1]
    rotation_range=20,        # Random rotation ±20 degrees
    zoom_range=0.2,           # Random zoom
    shear_range=0.2,          # Shear transformation
    horizontal_flip=True      # Flip images horizontally
)

# Validation & Test data generators (no augmentation, only normalization)
test_val_datagen = ImageDataGenerator(rescale=1./255)

# --------------------------
# 2. Generate Batches of Images
# --------------------------
train_gen = train_datagen.flow_from_directory(
    train_dir,
    target_size=(224,224),   # Resize images to 224x224
    batch_size=32,
    class_mode='binary'      # Binary labels: Normal=0, Pneumonia=1
)

val_gen = test_val_datagen.flow_from_directory(
    val_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary'
)

test_gen = test_val_datagen.flow_from_directory(
    test_dir,
    target_size=(224,224),
    batch_size=32,
    class_mode='binary',
    shuffle=False             # Do not shuffle test set for evaluation
)