# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1je6tGDz_8Ea_sHeKLKT8cKCqjJfers2k
"""

# preprocessing.py
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os

def create_generators(DATA_DIR):
    train_dir = os.path.join(DATA_DIR, 'train')
    val_dir   = os.path.join(DATA_DIR, 'val')
    test_dir  = os.path.join(DATA_DIR, 'test')

    train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=20,
        zoom_range=0.2,
        shear_range=0.2,
        horizontal_flip=True
    )

    test_val_datagen = ImageDataGenerator(rescale=1./255)

    train_gen = train_datagen.flow_from_directory(
        train_dir, target_size=(128,128), batch_size=32, class_mode='binary'
    )
    val_gen = test_val_datagen.flow_from_directory(
        val_dir, target_size=(128,128), batch_size=32, class_mode='binary'
    )
    test_gen = test_val_datagen.flow_from_directory(
        test_dir, target_size=(128,128), batch_size=32, class_mode='binary', shuffle=False
    )

    return train_gen, val_gen, test_gen