# -*- coding: utf-8 -*-
"""preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Yd8xm6OwJsuaFtT08fnZiFeTkYW_T9Yt
"""

from tensorflow.keras.preprocessing.image import ImageDataGenerator
import os
import random
import shutil

def prepare_validation_split(DATA_DIR, split_ratio=0.15):
    val_dir = os.path.join(DATA_DIR, 'val_fixed')
    os.makedirs(val_dir, exist_ok=True)
    classes = ['NORMAL', 'PNEUMONIA']

    for cls in classes:
        src = os.path.join(DATA_DIR, 'train', cls)
        dst = os.path.join(val_dir, cls)
        os.makedirs(dst, exist_ok=True)

        files = [f for f in os.listdir(src) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]
        random.shuffle(files)

        n_val = max(int(len(files) * split_ratio), 50)
        for f in files[:n_val]:
            shutil.copy(os.path.join(src, f), os.path.join(dst, f))

    print(f"✅ Validation folder created at {val_dir}")
    return val_dir


def create_generators(DATA_DIR):
    train_dir = os.path.join(DATA_DIR, 'train')
    val_dir   = os.path.join(DATA_DIR, 'val_fixed')
    test_dir  = os.path.join(DATA_DIR, 'test')

    train_datagen = ImageDataGenerator(
        rescale=1./255,
        rotation_range=20,
        zoom_range=0.2,
        shear_range=0.2,
        width_shift_range=0.1,
        height_shift_range=0.1,
        brightness_range=[0.8, 1.2],
        horizontal_flip=True,
        fill_mode='nearest'
    )

    test_val_datagen = ImageDataGenerator(rescale=1./255)

    train_gen = train_datagen.flow_from_directory(
        train_dir, target_size=(128,128), batch_size=16, class_mode='binary', shuffle=True
    )
    val_gen = test_val_datagen.flow_from_directory(
        val_dir, target_size=(128,128), batch_size=16, class_mode='binary', shuffle=False
    )
    test_gen = test_val_datagen.flow_from_directory(
        test_dir, target_size=(128,128), batch_size=16, class_mode='binary', shuffle=False
    )

    return train_gen, val_gen, test_gen